#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec  1 17:12:41 2021

@author: andre
"""

KEY_YES = 'Sim'
KEY_NOT = 'Não'

DEFAULT_KEY_MINIMUM_WAGE = '<<-SALARIO_MINIMO->>'
DEFAULT_KEY_TABLE_SETTINGS = '<<-DEFAULT_KEY_TABLE_SETTING->>'
DEFAULT_KEY_FAMILY_INCOME_LESS_THAN = '<<-RENDA_FAMILIAR_INFERIOR_A->>'
DEFAULT_KEY_OWN_BATCH_OF_UP_TO = '<<-POSSUIR_LOTE_DE_ATE->>'
DEFAULT_KEY_AMOUNT_REAL_ESTATE_URVAN = '<<-QUANTIA_DE_IMOVEIS_URBANO_DE->>'
DEFAULT_KEY_OWN_RURAL_PROPERTY = '<<-DEVE_POSSUIR_IMOVEL_RURAL->>'
DEFAULT_KEY_REURB_S = '<<-REURB-S->>'
DEFAULT_KEY_REURB_E = '<<-REURB-E->>'

DEFAULT_KEY_NAME_PROJECT = '<<-NOME_PROJETO->>'